---
name: Release Images

on:
  push:
    branches:
      - release-0.10
      - release-*

jobs:
  release:
    name: Release Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build and release new images
        uses: ./gh-actions/release-images
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
